### ISSUE TITLE
Windows CMake guide, how to use non-default CUDA version

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU2-docs#111]
This would be useful as personal reference to myself.

I did it once before.

It involves passing something to the "toolset" box when first configuring/selecting compiler. Will need to research the exact argument required.

https://cmake.org/cmake/help/latest/variable/CMAKE_VS_PLATFORM_TOOLSET_CUDA.html

Appears it could be as simple as providing `cuda=10.0` or similar in that box (or via command line)

**Comment by ptheywood** [comment]
The CLI for this looks like it would be `-T cuda=11.0` or similar, or comma's to separate other toolset options if needed. It's not something I've used before so will need testing by someone with a multi-cuda windows install.

https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR_TOOLSET.html#variable:CMAKE_GENERATOR_TOOLSET

It's probably not worth documenting how to combine it with other options, and reffering to the above URI for anyone that needs to select a specific VS toolset, or add things to the `VCTargetsPath` (`host` is not a valid option for CUDA which is exclusivly x64 on windows IIRC)

**Comment by Robadob** [comment]
Yeah have tested this and it's a case of passing `cuda=10.0` or similar to -T

![image](https://user-images.githubusercontent.com/742154/204572919-a77374d3-e904-40a3-aebb-7f52c053ace5.png)

```
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19044.
Looking for a CXX compiler
Looking for a CXX compiler - C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
The CXX compiler identification is MSVC 19.26.28805.0
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Looking for a CUDA compiler
Looking for a CUDA compiler - C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin/nvcc.exe
CMake Warning at C:/Program Files/CMake/share/cmake-3.21/Modules/CMakeDetermineCUDACompiler.cmake:15 (message):
  Visual Studio does not support specifying CUDAHOSTCXX or
  CMAKE_CUDA_HOST_COMPILER.  Using the C++ compiler provided by Visual
  Studio.
Call Stack (most recent call first):
  cmake/CheckCompilerFunctionality.cmake:24 (enable_language)
  cmake/CheckCompilerFunctionality.cmake:115 (CheckCompilerFunctionality)
  CMakeLists.txt:20 (include)


The CUDA compiler identification is NVIDIA 10.1.168
```
