### ISSUE TITLE
Beginner's feedback for improving documentation

### ISSUE THREAD

**Issue by bytetec** [FLAMEGPU/FLAMEGPU2-docs#158]
A few things I notice while using FLAMEGPU2 pure Python:
- Where do I place the setAgentOutput? Some hints would be nice. (Agent Functions::Agent Birth & Death::Enabling Agent Birth)
- The code snippets and the code summery do not fit together. Sometimes it is a model with 2 dimensions, sometimes one with 3 dimensions. (Tutorial)
- How is a HostFunction called / started by an agent? (Agent Functions or Hosts Function & Conditions)
- Move text about new FLAMEGPU2 functionality of environment macro properties to the Defining Macro Properties section. (Environmental Properties)
- What is a submodel and how is it used? Especially comparing with layers. (Defining Execution Order::Submodels)
- Some kind of overview or graphic how the different components like model, agents, functions, submodels and execution order interact with each other. (User Guide)

I’m happy to help and explain in further detail, if necessary.
And thank you in advance for considering my feedback.
Best bytetec

**Comment by Robadob** [comment]
Suggestions are always welcome, it can be hard for us as developers to see things from a user's perspective.

> Where do I place the setAgentOutput? Some hints would be nice. (Agent Functions::Agent Birth & Death::Enabling Agent Birth)

It must be called on the relevant agent functions `AgentFunctionDescription`. The actual location should not matter, so long as it's before you pass the `ModelDescription` to the `CUDASimulation` or `CUDAEnsemble`.

> The code snippets and the code summery do not fit together. Sometimes it is a model with 2 dimensions, sometimes one with 3 dimensions. (Tutorial)

The tutorial is supposed to be in 2 dimensions.

I think you're referring to agents having a `z` variable, this is a mistake and I will correct it.

> How is a HostFunction called / started by an agent? (Agent Functions or Hosts Function & Conditions)

Host functions execute at a global level, they are not started by agents. They occur in the control flow as defined via layers or the dependency graph.

> What is a submodel and how is it used? Especially comparing with layers. (Defining Execution Order::Submodels)

This should already be explained [here](https://docs.flamegpu.com/guide/defining-execution-order/submodels.html) on the page you referenced.

All that would be missing here, that I can see, would be an example of a submodel. We typically use them for iterative models, such as a generic cell-cell force model which runs until a steady state is reached, within a larger biological model. It would not be possible to implement such behaviour without a submodel.

> Some kind of overview or graphic how the different components like model, agents, functions, submodels and execution order interact with each other. (User Guide)

This is a good idea, we already have some graphics that we've used in presentations, e.g. below, it shouldn't be too difficult to provide a more thorough introduction in the docs.

I'll try and address these points soon (might not be until next week), please let me know if you think there's anything I've missed or misunderstood.

Thanks

------------
![image](https://github.com/FLAMEGPU/FLAMEGPU2-docs/assets/742154/023f04c7-59c0-4488-9c96-7579f559f1ce)
![image](https://github.com/FLAMEGPU/FLAMEGPU2-docs/assets/742154/51f82a4c-666c-4cf5-851d-3d4cdab45928)
![image](https://github.com/FLAMEGPU/FLAMEGPU2-docs/assets/742154/25128ac7-d33e-42c7-b866-5698d07ed2b1)
![image](https://github.com/FLAMEGPU/FLAMEGPU2-docs/assets/742154/3c2d1c16-7ecb-425b-989b-f9cb60a2cb68)
![image](https://github.com/FLAMEGPU/FLAMEGPU2-docs/assets/742154/4d340fdc-9f52-4849-a7ca-d31487da9558)
![image](https://github.com/FLAMEGPU/FLAMEGPU2-docs/assets/742154/2b84516b-5f53-4038-8ed4-dd01f60603ef)
![image](https://github.com/FLAMEGPU/FLAMEGPU2-docs/assets/742154/1f07b113-aa0d-4e93-8ccf-61b8a6c3589f)

**Comment by bytetec** [comment]
@Robadob Thanks for the enhancement of the documentation. 
The first 4 point are addressed from my perspective in #161. The sub model I do not understand yet. Please close that point, I can give you feedback later when I have a better understanding. But currently, I do not know how to get the better understanding :thinking:  

The first diagram shows a good overview of the components, do they have also specific relationships (arrows)? Second diagram is perfect, very understandable which messages strategy is available. Third diagram has also a Z variable. Fourth and fifth diagram are ok. In the sixth diagram why is the sub model not part of the layer explanation? And only agent functions are explained, what about the host functions. I like the seventh diagram, but without the Z variable.

**Comment by Robadob** [comment]
> The sub model I do not understand yet. Please close that point, I can give you feedback later when I have a better understanding. But currently, I do not know how to get the better understanding 🤔

We don't currently have a Python example that makes use of submodels, but you might be able to get an understanding of how they're applied from the C++ Sugarscape example.

https://github.com/FLAMEGPU/FLAMEGPU2/blob/master/examples/cpp/sugarscape/src/main.cu

> The first diagram shows a good overview of the components,

It's unclear at this stage what we'll do with the diagrams, lots to be discussed when the boss returns.

**Comment by bytetec** [comment]
I will try the sugarscape example. I also had a look at https://github.com/zeyus/FLAMEGPU2-Prisoners-Dilemma-ABM but no breakthrough yet.

**Comment by Robadob** [comment]
FYI: I've just drafted the section with the model structure and added it to the PR.

![image](https://github.com/FLAMEGPU/FLAMEGPU2-docs/assets/742154/f1381700-0aa4-41d1-b9b1-50407520e088)
