### ISSUE TITLE
List of supported types for Agent variables

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2-docs#51]
> For a complete list of supported types, see **TODO: reference page for available types**.

From `2-model-definition/3-agent.rst: Agent Variables`

**Comment by Robadob** [comment]
That file nolonger exists after the big refactor, but neither [Defining (Environment) Properties](https://docs.flamegpu.com/guide/environment/index.html#defining-properties) or[ Agent Variables](https://docs.flamegpu.com/guide/defining-agents/index.html#agent-variables).

Only recollection of discussing types is the [agent python docs](https://docs.flamegpu.com/guide/agent-functions/defining-agent-functions.html#typed-api-functions)
