### ISSUE TITLE
Restructure Messaging Docs

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2-docs#58]
As the number of messaging docs has grown, the splitting of output / input examples for each type seems less ideal / it is less clear how to use both input and output for a given type. 

Instead I propose:

1. A general description of messaging
    1. Include general output  and general input instructions, with bruteforce as the examples 
2. A table of the availabel types, with links to subsequent sections
3. For each messaging type:
    + Describe the shcheme and when it is appropriate for use / why it is a different type. 
    + Demonstrate defining the message description in C++ and python
    + Demonstrate output (agent functions are all CUDA C++)
    + Demonstrate input (agent functions are all CUDA C++). Include variants such as `.wrap()` where appropriate

**Comment by Robadob** [comment]
Will be resolved by #75
