### ISSUE TITLE
API documentation missing links

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2-docs#66]
In a number of places (atleast 6) there are links intending to link to API docs, which do not do so. 

The ones i've found are of the pattern: 

```rst
Full API documentation for the ``X``: link
```

Where `X` is the name of a class, such aas `EnvironmentDescription`.

We could hardcode links to the hosted API docs, but this feels brittle. There should be a breathe/exhale way of finding the correct link, although I'm not sure exactly how.

Additionally, as the api docs are an optional part of the docs project, these links will only exist if the API docs are being built, which is (suprisingly) expensive in terms or time.

+ [x] `src/guide/6-agent-birth-death/1-agent-birth-device.rst:149`
+ [x] `src/guide/6-agent-birth-death/3-agent-death.rst:53`
+ [x] `src/guide/2-model-definition/3-agent.rst:152`
+ [x] `src/guide/2-model-definition/2-environment.rst:137`
+ [x] `src/guide/2-model-definition/1-model.rst:31`
+ [x] `src/guide/3-behaviour-definition/1-defining-agent-functions.rst:170`

**Comment by Robadob** [comment]
Noticed some other issues on this page: https://docs.flamegpu.com/guide/3-behaviour-definition/6-host-functions.html

Bullets not formatted correctly: 
![image](https://user-images.githubusercontent.com/742154/152058937-4cb69fab-29c3-4ce3-811c-c3155fad9400.png)

Something odd going on around `uniform` here:

![image](https://user-images.githubusercontent.com/742154/152059064-b2ef5b03-4387-44f0-ba56-92da0ff4f7e7.png)

**Comment by Robadob** [comment]
https://exhale.readthedocs.io/en/latest/usage.html#linking-to-a-generated-file

This appears to be the guidance, will test.

**Comment by Robadob** [comment]
Ok so writing
```
* Full API documentation for the ``EnvironmentDescription``: :class:`flamegpu::EnvironmentDescription`
```
produces a link like this.
![image](https://user-images.githubusercontent.com/742154/152129119-b4c6c5c9-dfae-421e-bdf5-9d5a3678d6b9.png)

And the link goes to `api/classflamegpu_1_1_environment_description.html#_CPPv4N8flamegpu22EnvironmentDescriptionE`

![image](https://user-images.githubusercontent.com/742154/152129272-c1948722-831c-4bbc-b5aa-df540dfdd27f.png)

**Comment by Robadob** [comment]
And if you want custom text, you use something like this

```
* Full API documentation for the ``EnvironmentDescription``: :class:`custom text<flamegpu::EnvironmentDescription>`
```

Not clear how to get rid of the inline code style, but that's probably not an issue, this will just allow us to omit the namespace inline.

![image](https://user-images.githubusercontent.com/742154/152132900-591291eb-524a-4592-a707-7908166f29a4.png)

**Comment by Robadob** [comment]
The more info block at the bottom of `src/guide/6-agent-birth-death/3-agent-death.rst:53` isn't even relevant, it appears copy pasted from a page related to environment.
