### ISSUE TITLE
API Docs via CI

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2-docs#7]
Once issues with breeze have been resolved we should be able to include the API docs in the hosted userguide (via breeze). 

The main issue will be that the published docs are only updated when this repo is updated, rather than the [FLAMEGPU/FLAMEGPU2](https://github.com/flamegpu/flamegpu2) repo

**Comment by mondus** [comment]
We could trigger an action in this repo as part of our FGPU2 main repo build

**Comment by ptheywood** [comment]
I've added a `workflow_dispatch` trigger to the publish (and build) CI jobs, this means that they can be triggered using a button on workflows page (I assume only by authorised accounts)
